version: "3.8"

services:
  node1:
    build:
      context: .
    #      dockerfile: Dockerfile
    networks:
      lan_node1:
        ipv4_address: 192.168.10.100 # IP fija para el nodo 1 en su red privada
      public_network:
        ipv4_address: 172.20.0.3     # IP fija del nodo 1 en la red pública
    ports:
      - "4002:4002"
    environment:
      ORION_PORT: 4002
      ORION_FILES: "${ORION_FILES}"
      ORION_BOOTSTRAP_IP: "${ORION_BOOTSTRAP_IP}"
      ORION_BOOTSTRAP_PORT: "${ORION_BOOTSTRAP_PORT}"
      ORION_BOOTSTRAP_ID: "${ORION_BOOTSTRAP_ID}"
    command: >
      java
      -Dorion.files.scan.folder=$${ORION_FILES}
      -Dspring.profiles.active=pro
      -Dprism.order=sw
      -Djavafx.headless=true
      -Dglass.platform=Monocle
      -Dmonocle.platform=Headless
      -Dorion.p2p.limitK=20
      -Dorion.p2p.port=$${ORION_PORT}
      -Dorion.p2p.bootstrap-ip=$${ORION_BOOTSTRAP_IP}
      -Dorion.p2p.bootstrap-port=$${ORION_BOOTSTRAP_PORT}
      -Dorion.p2p.bootstrap-id=$${ORION_BOOTSTRAP_ID}
      -jar /app/orion-application.jar
      --enabled-ui="false"

  node2:
    build:
      context: .
    #      dockerfile: Dockerfile
    networks:
      lan_node2:
        ipv4_address: 192.168.11.101
      public_network:
        ipv4_address: 172.20.0.4
    ports:
      - "4003:4003" # Accesible desde puerto 5002 del host
    environment:
      ORION_PORT: 4003
      ORION_FILES: "${ORION_FILES}"
      ORION_BOOTSTRAP_IP: "${ORION_BOOTSTRAP_IP}"
      ORION_BOOTSTRAP_PORT: "${ORION_BOOTSTRAP_PORT}"
      ORION_BOOTSTRAP_ID: "${ORION_BOOTSTRAP_ID}"
    command: >
      java
      -Dorion.files.scan.folder=$${ORION_FILES}
      -Dprism.order=sw
      -Djavafx.headless=true
      -Dglass.platform=Monocle
      -Dmonocle.platform=Headless
      -Dorion.p2p.limitK=20
      -Dorion.p2p.port=$${ORION_PORT}
      -Dorion.p2p.bootstrap-ip=$${ORION_BOOTSTRAP_IP}
      -Dorion.p2p.bootstrap-port=$${ORION_BOOTSTRAP_PORT}
      -Dorion.p2p.bootstrap-id=$${ORION_BOOTSTRAP_ID}
      -jar /app/orion-application.jar
      --enabled-ui="false"

  node3:
    build:
      context: .
    #      dockerfile: Dockerfile
    networks:
      lan_node3:
        ipv4_address: 192.168.12.101 # IP fija para el nodo 1 en su red privada
      public_network:
        ipv4_address: 172.20.0.5     # IP fija del nodo 1 en la red pública
    ports:
      - "4004:4004" # Accesible desde puerto 5002 del host
    environment:
      ORION_PORT: 4004
      ORION_FILES: "${ORION_FILES}"
      ORION_BOOTSTRAP_IP: "${ORION_BOOTSTRAP_IP}"
      ORION_BOOTSTRAP_PORT: "${ORION_BOOTSTRAP_PORT}"
      ORION_BOOTSTRAP_ID: "${ORION_BOOTSTRAP_ID}"
    command: >
      java
      -Dorion.files.scan.folder=$${ORION_FILES}
      -Dprism.order=sw
      -Djavafx.headless=true
      -Dglass.platform=Monocle
      -Dmonocle.platform=Headless
      -Dorion.p2p.limitK=20
      -Dorion.p2p.port=$${ORION_PORT}
      -Dorion.p2p.bootstrap-ip=$${ORION_BOOTSTRAP_IP}
      -Dorion.p2p.bootstrap-port=$${ORION_BOOTSTRAP_PORT}
      -Dorion.p2p.bootstrap-id=$${ORION_BOOTSTRAP_ID}
      -jar /app/orion-application.jar
      --enabled-ui="false"

networks:
  lan_node1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24 # Nodo 1 simula estar en una red 192.168.10.x
  lan_node2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
  lan_node3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
  public_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
