spring:
  application:
    name: orion-application
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:sqlite:application.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:database/tables01.sql #todo ESTO ES LA BD , HAY QUE PONERLA EN OTRO DIRECTORIO, AHORA ESTA EN TARGET

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info
    io.libp2p.core: debug
    com.mac.orion: INFO

    io:
      libp2p:
        protocol:
          Identify: debug
orion:
#  files:
#    scan:
#      folder: >
#        ${USERPROFILE}/ORION-FILES/share
#    temp:
#      folder: ${TMP_FOLDER}
#    download:
#      folder: ${DOWNLOAD_FOLDER}
  p2p:
    limitK: 20
    bootstrap-ip: "" #172.20.0.3
    bootstrap-port: 8000 #172.20.0.3
    bootstrap-id: "" #172.20.0.3

