spring:
  application:
    name: orion-application
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:sqlite:application.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:database/tables01.sql

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
    io.libp2p.core: info
    com.mac.orion: info

orion:
#  files:
#    scan:
#      folder:
#        - D:\Download\ORION-FILES\share
#        - C:\Users\jaluque\Downloads\ORION-FILES\share
#    temp:
#      folder: ${TMP_FOLDER}
#    download:
#      folder: ${DOWNLOAD_FOLDER}
  user-profile: ${USERPROFILE}
  p2p:
    port: 4050
    limitK: 20
    bootstrap-ip: 127.0.0.1 #172.20.0.3
    bootstrap-port: 5050 #172.20.0.3
    bootstrap-id: "QmPX2kfWeCRL3QmuYJTRTkpq3hXgVQH33fNox6G7n7QHJp" #172.20.0.3
